--   פּ ﯟ   some other good icons
return {
	Text = '',
	Method = 'm',
	-- Function = '',
	Function = '',
	Constructor = '',
	Field = '',
	Variable = '',
	Class = '',
	Interface = '',
	Module = '',
	Property = '',
	Unit = '',
	Value = '',
	Enum = '',
	Keyword = '',
	Snippet = '',
	Color = '',
	File = '',
	Reference = '',
	Folder = '',
	EnumMember = '',
	Constant = '',
	Struct = '',
	Event = '',
	Operator = '',
	-- TypeParameter = '',
	TypeParameter = '',
	cmdline_history = '',
}
