return {
	-- auto_reload_on_write = true,
	-- create_in_closed_folder = false,
	-- disable_netrw = false,
	-- hijack_cursor = false,
	-- hijack_netrw = true,
	-- hijack_unnamed_buffer_when_opening = false,
	-- ignore_buffer_on_setup = false,
	-- open_on_setup = false,
	-- open_on_setup_file = false,
	-- open_on_tab = false,
	-- focus_empty_on_setup = false,
	-- ignore_buf_on_tab_change = {},
	-- sort_by = 'name',
	-- root_dirs = {},
	prefer_startup_root = true,
	sync_root_with_cwd = true,
	reload_on_bufenter = true,
	respect_buf_cwd = false,
	on_attach = 'disable',
	remove_keymaps = false,
	select_prompts = false,
	view = {
		adaptive_size = false,
		centralize_selection = false,
		width = 30,
		hide_root_folder = false,
		side = 'left',
		preserve_window_proportions = false,
		number = false,
		relativenumber = false,
		signcolumn = 'yes',
		mappings = {
			custom_only = true,
		},
		float = {
			enable = true,
			open_win_config = {
				relative = 'win', -- editor | win | cursor
				border = 'rounded', -- none | single | double | rounded | solid | shadow
				-- border = { "A", "B", "C", "D" },
				-- border = { "A", "B", "C", "D", "E", "F", "G", "H" },
				-- border = { " ", " ", " ", " ", "", "", "", "" },
				row = -1,
				col = 1,
				-- anchor = 'NE',
				-- row = 0,
				-- col = vim.api.nvim_win_get_width(0) - 35,

				width = 35,
				height = vim.api.nvim_win_get_height(0) - 2,
			},
		},
	},
	renderer = {
		add_trailing = false,
		group_empty = true,
		highlight_git = false,
		full_name = false,
		highlight_opened_files = 'yes',
		root_folder_modifier = ':~',
		indent_width = 2,
		indent_markers = {
			enable = true,
			inline_arrows = true,
			icons = {
				corner = '└',
				edge = '│',
				item = '│',
				bottom = '─',
				none = ' ',
			},
		},
		icons = {
			webdev_colors = true,
			git_placement = 'before',
			padding = ' ',
			symlink_arrow = ' ➛ ',
			show = {
				file = true,
				folder = true,
				folder_arrow = true,
				git = true,
			},
			glyphs = {
				default = '',
				symlink = '',
				bookmark = '',
				folder = {
					arrow_closed = '',
					arrow_open = '',
					default = '',
					open = '',
					empty = '',
					empty_open = '',
					symlink = '',
					symlink_open = '',
				},
				git = {
					staged = 'S',
					unstaged = '',
					untracked = 'U',

					-- unstaged = "✗",
					-- staged = "✓",
					-- untracked = "★",

					unmerged = '',
					renamed = '➜',
					deleted = '',
					ignored = '◌',
				},
			},
		},
		special_files = { 'Cargo.toml', 'Makefile', 'README.md', 'readme.md' },
		symlink_destination = true,
	},
	hijack_directories = {
		enable = true,
		auto_open = true,
	},
	update_focused_file = {
		enable = false,
		update_root = false,
		ignore_list = {},
		update_cwd = false,
	},
	ignore_ft_on_setup = {},
	system_open = {
		cmd = '',
		args = {},
	},
	diagnostics = {
		enable = false,
		show_on_dirs = false,
		debounce_delay = 50,
		icons = {
			hint = '',
			info = '',
			warning = '',
			error = '',
		},
	},
	filters = {
		dotfiles = false,
		custom = {},
		exclude = {},
	},
	filesystem_watchers = {
		enable = true,
		debounce_delay = 50,
	},
	git = {
		enable = true,
		ignore = false,
		show_on_dirs = true,
		timeout = 400,
	},
	actions = {
		use_system_clipboard = true,
		change_dir = {
			enable = true,
			global = false,
			restrict_above_cwd = true,
		},
		expand_all = {
			max_folder_discovery = 300,
			exclude = {},
		},
		file_popup = {
			open_win_config = {
				col = 1,
				row = 1,
				relative = 'cursor',
				border = 'rounded',
				style = 'minimal',
			},
		},
		open_file = {
			quit_on_open = false,
			resize_window = true,
			window_picker = {
				enable = true,
				-- chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
				chars = 'asdfjkl;',
				exclude = {
					filetype = { 'notify', 'packer', 'qf', 'diff', 'fugitive', 'fugitiveblame' },
					buftype = { 'nofile', 'terminal', 'help' },
				},
			},
		},
		remove_file = {
			close_window = false,
		},
	},
	trash = {
		cmd = 'gio trash',
		require_confirm = true,
	},
	live_filter = {
		prefix = '[FILTER]: ',
		always_show_folders = true,
	},
	log = {
		enable = false,
		truncate = false,
		types = {
			all = false,
			config = false,
			copy_paste = false,
			dev = false,
			diagnostics = false,
			git = false,
			profile = false,
			watcher = false,
		},
	},
}
