require 'lua.plugins.autopairs'
require 'lua.plugins.bufferline'
require 'lua.plugins.cmp'
require 'lua.plugins.gitsigns'
require 'lua.plugins.harpoon'
require 'lua.plugins.nvim-tree'
-- require 'lua.plugins.treesitter'
require 'lua.plugins.whichkey'
