require 'lua.plugins.comment'
-- require 'lua.plugins.autopairs'
-- require 'lua.plugins.bufferline'
-- require 'lua.plugins.cmp'
-- require 'lua.plugins.dadbod'
-- require 'lua.plugins.git.diffview'
-- require 'lua.plugins.git.gitsigns'
-- require 'lua.plugins.git.neogit'
-- require 'lua.plugins.harpoon'

-- require 'lua.plugins.lspsaga.config'
-- require 'lua.plugins.lspsaga.keymaps'
-- require 'lua.plugins.lspsaga.winbar'

-- require 'lua.plugins.luasnip.luasnip'
-- require 'lua.plugins.luasnip.snippets'

-- require 'lua.plugins.neotest'
-- require 'lua.plugins.tree.functions'
-- require 'lua.plugins.tree.mappings'
-- require 'lua.plugins.tree.options'
-- require 'lua.plugins.tree.setup'
-- require 'lua.plugins.treesitter.completion'
-- require 'lua.plugins.treesitter.context'
-- require 'lua.plugins.treesitter.playground'
-- require 'lua.plugins.treesitter.selection'
-- require 'lua.plugins.treesitter.textobjects'
-- require 'lua.plugins.treesitter.treesitter'
-- require 'lua.plugins.treesitter.visual'
-- require 'lua.plugins.whichkey'
