column_width = 100
quote_style = 'AutoPreferSingle' # AutoPreferDouble, AutoPreferSingle, ForceDouble, ForceSingle
call_parentheses = 'NoSingleTable' # Always, NoSingleString, NoSingleTable, None
collapse_simple_statement = 'ConditionalOnly' # Never, FunctionOnly, ConditionalOnly, or Always
