let $path = $HOME.'/.config/nvim/vim'

fun! SourceDir(dir_name)
	let $dir_path = $path.'/'.a:dir_name.'/*.vim'

	for f in split(glob($dir_path), '\n')
		exe 'source' f
	endfor
endfun

call SourceDir('functions')
call SourceDir('key_bindings')
call SourceDir('plugins')


" source $path/plugins/plugins.vim
" source $path/plugins/vimwiki.vim
" source $path/plugins/goyo.vim
" source $path/plugins/gitgutter.vim
" source $path/plugins/lightline.vim
" source $path/plugins/limelight.vim
" source $path/plugins/ranger.vim
" source $path/plugins/startify.vim
" source $path/plugins/quickscope.vim

source $path/sets.vim
source $path/functions.vim
source $path/user_interface.vim
source $path/misc.vim
source $path/colors.vim
source $path/autocmds.vim

if exists('g:neovide')
	source $path/neovide.vim
endif

